baseURL = 'https://myhugodemosite.netlify.app'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10
  background_color_class = "bg-dark-green"


[params]
  text_color = "White"
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-light-purple "
  recent_posts_number = 3
