baseURL = 'https://myhugodemosite.netlify.app'
languageCode = 'en-us'
title = 'Christmas'
theme = 'ananke'



[params]
  text_color = "White"
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  background_color_class = "bg-dark-red"
  recent_posts_number = 3